//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.10 at 03:15:13 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:yahoo:answers", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package yahoo.answers;
