//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.10 at 03:15:13 AM ICT 
//


package yahoo.answers;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:yahoo:answers}Subject"/>
 *         &lt;element ref="{urn:yahoo:answers}Content"/>
 *         &lt;element ref="{urn:yahoo:answers}Date"/>
 *         &lt;element ref="{urn:yahoo:answers}Timestamp"/>
 *         &lt;element ref="{urn:yahoo:answers}Link"/>
 *         &lt;element ref="{urn:yahoo:answers}Category"/>
 *         &lt;element ref="{urn:yahoo:answers}UserId"/>
 *         &lt;element ref="{urn:yahoo:answers}UserNick"/>
 *         &lt;element ref="{urn:yahoo:answers}UserPhotoURL"/>
 *         &lt;element ref="{urn:yahoo:answers}NumAnswers"/>
 *         &lt;element ref="{urn:yahoo:answers}NumComments"/>
 *         &lt;element ref="{urn:yahoo:answers}ChosenAnswer"/>
 *         &lt;element ref="{urn:yahoo:answers}ChosenAnswererId"/>
 *         &lt;element ref="{urn:yahoo:answers}ChosenAnswererNick"/>
 *         &lt;element ref="{urn:yahoo:answers}ChosenAnswerTimestamp"/>
 *         &lt;element ref="{urn:yahoo:answers}ChosenAnswerAwardTimestamp"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subject",
    "content",
    "date",
    "timestamp",
    "link",
    "category",
    "userId",
    "userNick",
    "userPhotoURL",
    "numAnswers",
    "numComments",
    "chosenAnswer",
    "chosenAnswererId",
    "chosenAnswererNick",
    "chosenAnswerTimestamp",
    "chosenAnswerAwardTimestamp"
})
@XmlRootElement(name = "Question")
public class Question {

    @XmlElement(name = "Subject", required = true)
    protected String subject;
    @XmlElement(name = "Content", required = true)
    protected String content;
    @XmlElement(name = "Date", required = true)
    protected String date;
    @XmlElement(name = "Timestamp", required = true)
    protected BigInteger timestamp;
    @XmlElement(name = "Link", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String link;
    @XmlElement(name = "Category", required = true)
    protected Category category;
    @XmlElement(name = "UserId", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String userId;
    @XmlElement(name = "UserNick", required = true)
    protected String userNick;
    @XmlElement(name = "UserPhotoURL", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String userPhotoURL;
    @XmlElement(name = "NumAnswers", required = true)
    protected BigInteger numAnswers;
    @XmlElement(name = "NumComments", required = true)
    protected BigInteger numComments;
    @XmlElement(name = "ChosenAnswer", required = true)
    protected String chosenAnswer;
    @XmlElement(name = "ChosenAnswererId", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String chosenAnswererId;
    @XmlElement(name = "ChosenAnswererNick", required = true)
    protected String chosenAnswererNick;
    @XmlElement(name = "ChosenAnswerTimestamp", required = true)
    protected BigInteger chosenAnswerTimestamp;
    @XmlElement(name = "ChosenAnswerAwardTimestamp", required = true)
    protected BigInteger chosenAnswerAwardTimestamp;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String id;
    @XmlAttribute(name = "type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String type;

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubject(String value) {
        this.subject = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTimestamp(BigInteger value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLink(String value) {
        this.link = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link Category }
     *     
     */
    public Category getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link Category }
     *     
     */
    public void setCategory(Category value) {
        this.category = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the userNick property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserNick() {
        return userNick;
    }

    /**
     * Sets the value of the userNick property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserNick(String value) {
        this.userNick = value;
    }

    /**
     * Gets the value of the userPhotoURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserPhotoURL() {
        return userPhotoURL;
    }

    /**
     * Sets the value of the userPhotoURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserPhotoURL(String value) {
        this.userPhotoURL = value;
    }

    /**
     * Gets the value of the numAnswers property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumAnswers() {
        return numAnswers;
    }

    /**
     * Sets the value of the numAnswers property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumAnswers(BigInteger value) {
        this.numAnswers = value;
    }

    /**
     * Gets the value of the numComments property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumComments() {
        return numComments;
    }

    /**
     * Sets the value of the numComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumComments(BigInteger value) {
        this.numComments = value;
    }

    /**
     * Gets the value of the chosenAnswer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChosenAnswer() {
        return chosenAnswer;
    }

    /**
     * Sets the value of the chosenAnswer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChosenAnswer(String value) {
        this.chosenAnswer = value;
    }

    /**
     * Gets the value of the chosenAnswererId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChosenAnswererId() {
        return chosenAnswererId;
    }

    /**
     * Sets the value of the chosenAnswererId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChosenAnswererId(String value) {
        this.chosenAnswererId = value;
    }

    /**
     * Gets the value of the chosenAnswererNick property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChosenAnswererNick() {
        return chosenAnswererNick;
    }

    /**
     * Sets the value of the chosenAnswererNick property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChosenAnswererNick(String value) {
        this.chosenAnswererNick = value;
    }

    /**
     * Gets the value of the chosenAnswerTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChosenAnswerTimestamp() {
        return chosenAnswerTimestamp;
    }

    /**
     * Sets the value of the chosenAnswerTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChosenAnswerTimestamp(BigInteger value) {
        this.chosenAnswerTimestamp = value;
    }

    /**
     * Gets the value of the chosenAnswerAwardTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChosenAnswerAwardTimestamp() {
        return chosenAnswerAwardTimestamp;
    }

    /**
     * Sets the value of the chosenAnswerAwardTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChosenAnswerAwardTimestamp(BigInteger value) {
        this.chosenAnswerAwardTimestamp = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
